### ISSUE TITLE
Add support for `epel8-next` and `epel9-next`

### ISSUE THREAD

**Issue by gotmax23** [juhp/fbrnch#29] opened 2022-02-22 22:32 UTC
When I run `fbrnch build epel8-next`, the tool does not detect that `epel8-next` is a branch name and returns `fbrnch: No such directory: epel8-next`.

**Comment by juhp** [comment] 2022-05-17 04:24
I have actually done a local implementation of this now, but I haven't really tested since I don't really use epel-next much.

If you are able to build & test it from git before I make a release I can push it I think.

**Comment by gotmax23** [comment] 2022-05-17 14:03
> If you are able to build & test it from git before I make a release I can push it in a buildable form now I think.

Yeah, I can rebuild the Fedora RPM with a diffefent source tarball (I'm not familiar with the actual Haskell tools :)) and test it. If you prefer to submit it as a PR first, that works too.

**Comment by juhp** [comment] 2022-05-18 07:37
Well the problem is I have yet to release the new fedora-dists - so you would only be able to build from git source at the moment.
(I have been pondering to revive my copr since the release process is becoming rather slower than I wish...).

**Comment by gotmax23** [comment] 2022-05-18 15:12
> Well the problem is I have yet to release the new fedora-dists - so you would only be able to build from git source at the moment. (I have been pondering to revive my copr since the release process is becoming rather slower than I wish...).
> 
> (You could more or less do: `dnf builddep fbrnch` and then `cabal install` in the source here (once I push the changes).)

I'm trying this:
``` patch
diff --git a/fbrnch.spec b/fbrnch.spec
index 292bec3..51b97b1 100644
--- a/fbrnch.spec
+++ b/fbrnch.spec
@@ -4,15 +4,19 @@
 %global bodhi bodhi-0.1.0
 %global cachedjsonfile cached-json-file-0.1.1
 %global coprapi copr-api-0.1.0
-%global fedoradists fedora-dists-2.0.0
+%global fedoradists fedora-dists-2.1.0
 %global pagure pagure-0.1.1
 %global pdc pdc-0.1.1
 %global subpkgs %{bodhi} %{coprapi} %{cachedjsonfile} %{pdc} %{fedoradists} %{pagure}
 
+%global commit   ecfd9c901449cc5c613be2d089dbcfbd2ab8003d
+%global forgeurl https://github.com/juhp/fbrnch
+%forgemeta
+
 Name:           fbrnch
 Version:        1.1
 # can only be reset when all subpkgs bumped
-Release:        2%{?dist}
+Release:        3%{?dist}
 Summary:        Fedora packager tool to build package branches
 
 # bodhi-hs, pdc-hs: MIT
@@ -21,7 +25,8 @@ Summary:        Fedora packager tool to build package branches
 License:        GPLv2+ and MIT and GPLv3+
 Url:            https://hackage.haskell.org/package/%{name}
 # Begin cabal-rpm sources:
-Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz
+# Source0:        https://hackage.haskell.org/package/%%{name}-%%{version}/%%{name}-%%{version}.tar.gz
+Source0:        %{forgesource}
 Source1:        https://hackage.haskell.org/package/%{bodhi}/%{bodhi}.tar.gz
 Source2:        https://hackage.haskell.org/package/%{cachedjsonfile}/%{cachedjsonfile}.tar.gz
 Source3:        https://hackage.haskell.org/package/%{coprapi}/%{coprapi}.tar.gz
@@ -119,7 +124,7 @@ and many more commands.
 
 %prep
 # Begin cabal-rpm setup:
-%setup -q -a1 -a2 -a3 -a4 -a5 -a6
+%setup -q %{forgesetupargs} -a1 -a2 -a3 -a4 -a5 -a6
 # End cabal-rpm setup
 
 

```

I would happily use a copr repo that builds from `main`. I think there's some way to configure copr to rebuild the package automatically each time you push to Github.

> Or maybe you can point me at some example package(s) with active epel-next branches that I can just try it on them (obviously I am not going actually to build anything, but I can try some commands or use --dryrun etc).

`ansible`, which I co-maintain, has both an epel8-next and an epel9-next branch.

**Comment by gotmax23** [comment] 2022-05-18 15:19
> I'm trying this:

Is there also a corresponding update in `fbrnch` that you haven't pushed yet?

**Comment by juhp** [comment] 2022-05-18 16:35
Yeah just released fedora-dists, and I am still working on pushing fbrnch (but first newer simple-cmd, though it is not required here).

**Comment by juhp** [comment] 2022-05-18 17:02
Okay, thanks for waiting, I just pushed now.
I think you will need newer rpm-nvr now: but you can get that from updates-testing already.

**Comment by juhp** [comment] 2022-05-19 04:29
I see the problem - I think I have to do a new release of fedora-dists to address this.
(Again this is due to PDC not listing epel-next - maybe I should look at Bodhi again.)

**Comment by juhp** [comment] 2022-05-19 15:10
@gotmax23 maybe you can try applying this as a patch to fedora-dists?

It seemed to work for me somewhat this morning (despite the fedora dist-git problems, which are now fixed I think).

**Comment by gotmax23** [comment] 2022-05-19 16:27
> @gotmax23 maybe you can try applying this as a patch to fedora-dists?

I rebuilt this with https://github.com/juhp/fedora-dists/commit/30ac460ff0730c139a8adbdb3a5870c0bffc2be1.patch applied to fedora-dists.

I am testing a real epel8-next build right now. I noticed that `fbrnch nvr` determines the wrong nvr on epel*-next branches.

``` console
$ fbrnch nvr epel8-next
ansible-5.8.0-1.el8
$ fedpkg verrel
ansible-5.8.0-1.el8.next
```

**Comment by gotmax23** [comment] 2022-05-19 16:28
`%dist` is `.el8.next` on `epel8-next` and `.el9.next` on `epel9-next`.

**Comment by juhp** [comment] 2022-05-19 16:58
Okay thanks - that's easy to fix!

**Comment by juhp** [comment] 2022-05-19 17:04
I may cut a new release for fedora-dists tomorrow or so, depending on how it looks.
Thanks for testing it.

**Comment by juhp** [comment] 2022-05-21 04:12
Okay thanks, I think I will do a new minor release of fedora-dists then.

**Comment by gotmax23** [comment] 2022-05-21 04:28
> Okay thanks, I think I will do a new minor release of fedora-dists then.

+1. 

I don't have any more epel*-next updates to test, but I'll let you know if anything goes awry on the next one.

**Comment by juhp** [comment] 2022-05-24 16:42
2.1.1 is now on Hackage

**Closed by juhp** 2022-05-24 16:42 UTC

**Comment by gotmax23** [comment] 2022-05-26 19:23
> I don't have any more epel*-next updates to test right now, but I'll let you know if anything goes awry on the next one.

My latest epel9-next ansible update went flawlessly!
